.PHONY: setup-env setup-env-name \
        install install-dev \
        demo demo-all demo-bulkrna \
        test test-serial test-slow test-all \
        list skill-index \
        bot-telegram bot-multi bot-list

## ── Conda environment (recommended, full functionality) ──────────────
## Single-command install of R 4.3, ~130 R/Bioconductor packages, ~15
## bioconda CLIs, and OmicsClaw (editable) with its `full` and
## `singlecell-upstream` extras.
## Requires mamba (recommended) or conda — install Miniforge:
##   https://github.com/conda-forge/miniforge

setup-env:
	bash 0_setup_env.sh

# Use a custom env name: `make setup-env-name NAME=foo`
NAME ?= OmicsClaw
setup-env-name:
	bash 0_setup_env.sh "$(NAME)"

## ── pip install into the active environment ─────────────────────────────────
## Python only: R, samtools, STAR, fastqc and the science stack come from
## environment.yml (make setup-env).

install:
	pip install -e .

install-dev:
	pip install -e ".[dev]"

## ── Demo & test targets ──────────────────────────────────────────────────────

demo:
	python skills/spatial/spatial-preprocess/spatial_preprocess.py --demo --output /tmp/omicsclaw_demo

# Deterministic fast suite. Skill demo executions, optional scientific stacks,
# and real-LLM evaluations are separate because they have different dependency,
# runtime, and failure semantics. Override worker counts when needed.
PYTEST_WORKERS ?= 32
SCIENTIFIC_TEST_WORKERS ?= 4

test:
	python -m pytest -q -n $(PYTEST_WORKERS)

# Serial run, for debugging: -s/pdb and readable tracebacks need one process.
test-serial:
	python -m pytest -v

# Scientific/demo integration suite. Keep concurrency bounded: one scientific
# subprocess can import more than 1 GiB of native Python/R dependencies.
test-slow:
	python -m pytest -q -n $(SCIENTIFIC_TEST_WORKERS) -m "slow or demo"

# Everything except real-LLM evals. Intended for release/nightly verification.
test-all:
	python -m pytest -q -n $(SCIENTIFIC_TEST_WORKERS) -m "not eval"

# What the agent is actually shown: the skills the loader indexed, and
# anything it found and refused. `python omicsclaw.py list` was the retired
# CLI's registry dump and no longer runs.
list:
	@python -c "from omicsclaw.skills import load_skills; \
	  i = load_skills('skills'); \
	  print(f'{len(i)} skill(s), {len(i.skipped)} skipped'); \
	  print(i.domain_summary(), end='')"

# The skill catalogue, the `requires:` audit, the routing-surface drift
# check and the Skip-when eval snapshot were targets over
# scripts/generate_catalog.py, audit_skill_requires.py,
# check_description_drift.py and extract_skip_when_cases.py. All four
# belonged to the retired skill system and were deleted with it.
#
# What replaced them: a SKILL.md header is the only metadata there is, and
# the derived documents are checked by tests rather than regenerated by
# scripts.
skill-index:
	OMICSCLAW_WRITE_SKILL_INDEX=1 python -m pytest -q \
		tests/skills/test_domain_index_is_current.py

demo-all:
	python skills/spatial/spatial-preprocess/spatial_preprocess.py --demo --output /tmp/sc_preprocess
	python skills/spatial/spatial-domains/spatial_domains.py --demo --output /tmp/sc_domains
	python skills/spatial/spatial-de/spatial_de.py --demo --output /tmp/sc_de
	python skills/spatial/spatial-genes/spatial_genes.py --demo --output /tmp/sc_genes
	python skills/spatial/spatial-statistics/spatial_statistics.py --demo --output /tmp/sc_statistics
	python skills/spatial/spatial-annotate/spatial_annotate.py --demo --output /tmp/sc_annotate
	python skills/spatial/spatial-deconv/spatial_deconv.py --demo --output /tmp/sc_deconv
	python skills/spatial/spatial-communication/spatial_communication.py --demo --output /tmp/sc_communication
	python skills/spatial/spatial-condition/spatial_condition.py --demo --output /tmp/sc_condition
	python skills/spatial/spatial-velocity/spatial_velocity.py --demo --output /tmp/sc_velocity
	python skills/spatial/spatial-trajectory/spatial_trajectory.py --demo --output /tmp/sc_trajectory
	python skills/spatial/spatial-enrichment/spatial_enrichment.py --demo --output /tmp/sc_enrichment
	python skills/spatial/spatial-cnv/spatial_cnv.py --demo --output /tmp/sc_cnv
	python skills/spatial/spatial-integrate/spatial_integrate.py --demo --output /tmp/sc_integrate
	python skills/spatial/spatial-register/spatial_register.py --demo --output /tmp/sc_register

demo-bulkrna:
	python skills/bulkrna/bulkrna-read-alignment/bulkrna_read_alignment.py --demo --output /tmp/bulkrna_alignment
	python skills/bulkrna/bulkrna-de/bulkrna_de.py --demo --output /tmp/bulkrna_de
	python skills/bulkrna/bulkrna-splicing/bulkrna_splicing.py --demo --output /tmp/bulkrna_splicing
	python skills/bulkrna/bulkrna-enrichment/bulkrna_enrichment.py --demo --output /tmp/bulkrna_enrichment
	python skills/bulkrna/bulkrna-deconvolution/bulkrna_deconvolution.py --demo --output /tmp/bulkrna_deconv
	python skills/bulkrna/bulkrna-coexpression/bulkrna_coexpression.py --demo --output /tmp/bulkrna_coexpr

## ── Bot targets ─────────────────────────────────────────────────────────────
## bot-telegram and bot-multi exit 1 unless OMICSCLAW_APPROVAL_TIMEOUT_S is set
## (commented out in .env.example); bot-multi also needs CHANNELS=a,b.

bot-telegram:
	oc channel --channels telegram

# Several adapters in one process share one session registry. Prefer one
# platform per process unless you actually want that, because `start_all`
# is all-or-nothing: one mistyped credential stops every channel named here.
bot-multi:
	oc channel --channels $(CHANNELS)

bot-list:
	oc channel --list
