"""``POST /chat/title``: a short title for a session's first message.

Request: ``{"schema_version": 1, "source_request_id": <32 lowercase hex>,
"user_text": <1..4096 characters>}``.

Answers ``(200, {"schema_version": 1, "title": ...})``, or a failure
``{"schema_version": 1, "error": {"code": ...}}`` with:

* 422 ``TITLE_REQUEST_INVALID`` — the request does not match the above;
* 502 ``TITLE_OUTPUT_INVALID`` — the model answered with no usable line;
* 504 ``TITLE_TIMEOUT`` — no answer within the timeout;
* 502 ``TITLE_PROVIDER_FAILED`` — the call raised.

The title is generated by the running provider with no tools.
"""

from __future__ import annotations

import asyncio
import logging
import re
from typing import Any, Final, Mapping

from omicsclaw.schema import Message, Role

__all__ = [
    "MAX_TITLE_CHARS",
    "MAX_TITLE_INPUT_CHARS",
    "TITLE_SCHEMA_VERSION",
    "TITLE_TIMEOUT_S",
    "clean_title",
    "generate_title",
]

_log = logging.getLogger(__name__)

TITLE_SCHEMA_VERSION: Final = 1
MAX_TITLE_INPUT_CHARS: Final = 4096
MAX_TITLE_CHARS: Final = 80
TITLE_TIMEOUT_S: Final = 30.0

_SOURCE_REQUEST_ID: Final = re.compile(r"[0-9a-f]{32}")
_SYSTEM_PROMPT: Final = (
    "Write a title for the user's message in the same language as the "
    "message, in at most 8 words, with no quotation marks and no final "
    "period. Reply with the title only."
)
_QUOTE_PAIRS: Final = (
    ('"', '"'),
    ("'", "'"),
    ("`", "`"),
    ("“", "”"),
    ("‘", "’"),
    ("「", "」"),
    ("『", "』"),
    ("《", "》"),
)


def _failure(status: int, code: str) -> tuple[int, dict[str, Any]]:
    return status, {"schema_version": TITLE_SCHEMA_VERSION, "error": {"code": code}}


def _valid(document: Mapping[str, Any]) -> str | None:
    """The user text of a well-formed request, else ``None``."""
    version = document.get("schema_version")
    if not isinstance(version, int) or isinstance(version, bool):
        return None
    if version != TITLE_SCHEMA_VERSION:
        return None
    source = document.get("source_request_id")
    if not isinstance(source, str) or not _SOURCE_REQUEST_ID.fullmatch(source):
        return None
    text = document.get("user_text")
    if not isinstance(text, str) or not text.strip() or len(text) > MAX_TITLE_INPUT_CHARS:
        return None
    return text


def clean_title(raw: str) -> str:
    """The first non-empty line of *raw*, without surrounding quotes, cut
    to :data:`MAX_TITLE_CHARS`."""
    line = next((part.strip() for part in raw.splitlines() if part.strip()), "")
    changed = True
    while changed and len(line) >= 2:
        changed = False
        for opening, closing in _QUOTE_PAIRS:
            if line.startswith(opening) and line.endswith(closing):
                line = line[len(opening) : -len(closing)].strip()
                changed = True
                break
    return line[:MAX_TITLE_CHARS].strip()


async def generate_title(
    app: Any,
    document: Mapping[str, Any],
    *,
    timeout_s: float = TITLE_TIMEOUT_S,
) -> tuple[int, dict[str, Any]]:
    """Answer one ``POST /chat/title`` request with ``(status, payload)``."""
    text = _valid(document)
    if text is None:
        return _failure(422, "TITLE_REQUEST_INVALID")
    messages = (
        Message(role=Role.SYSTEM, content=_SYSTEM_PROMPT),
        Message(role=Role.USER, content=text),
    )
    try:
        async with asyncio.timeout(timeout_s):
            provider = app.provider.bind(max_tokens=1024, thinking_budget_tokens=0)
            completion = await provider.generate(messages, None)
    except TimeoutError:
        return _failure(504, "TITLE_TIMEOUT")
    except Exception as exc:  # noqa: BLE001 - every failure has one code
        _log.warning("title generation failed: %s", type(exc).__name__)
        return _failure(502, "TITLE_PROVIDER_FAILED")
    title = clean_title(str(completion.message.content or ""))
    if not title:
        return _failure(502, "TITLE_OUTPUT_INVALID")
    return 200, {"schema_version": TITLE_SCHEMA_VERSION, "title": title}
