"""Shared OmicsClaw skill execution runner.

This module owns reusable skill execution behavior. The repository-root
``omicsclaw.py`` file remains the CLI wrapper, but surfaces that need to run a
skill should import ``run_skill`` from here.
"""

from __future__ import annotations

import json
import os
import re
import signal
import subprocess
import sys
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from omicsclaw.common.report import (
    build_output_dir_name,
    extract_method_name,
    load_result_json,
    write_output_readme,
)
from omicsclaw.core.registry import registry
from omicsclaw.core.skill_result import build_skill_run_result


OMICSCLAW_DIR = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = OMICSCLAW_DIR / "output"
PYTHON = sys.executable

if str(OMICSCLAW_DIR) not in sys.path:
    sys.path.insert(0, str(OMICSCLAW_DIR))

registry.load_all()
SKILLS = registry.skills
DOMAINS = registry.domains

_COLOUR = hasattr(sys.stdout, "isatty") and sys.stdout.isatty()
BOLD = "\033[1m" if _COLOUR else ""
GREEN = "\033[32m" if _COLOUR else ""
RED = "\033[31m" if _COLOUR else ""
CYAN = "\033[36m" if _COLOUR else ""
RESET = "\033[0m" if _COLOUR else ""

SPATIAL_PIPELINE = [
    "spatial-preprocess",
    "spatial-domains",
    "spatial-de",
    "spatial-genes",
    "spatial-statistics",
]


def _get_write_analysis_notebook():
    from omicsclaw.common.notebook_export import write_analysis_notebook

    return write_analysis_notebook


def resolve_skill_alias(skill_name: str) -> str:
    """Resolve a user-facing skill name or legacy alias to its canonical alias."""
    if skill_name in SKILLS:
        return SKILLS[skill_name].get("alias", skill_name)

    for skill_key, skill_info in SKILLS.items():
        legacy_aliases = skill_info.get("legacy_aliases", [])
        if skill_name in legacy_aliases:
            return skill_key

    if ":" in skill_name:
        _domain, skill = skill_name.split(":", 1)
        if skill in SKILLS:
            return skill

    return skill_name


def _extract_flag_value(tokens: list[str] | None, flag: str) -> str | None:
    """Extract a forwarded flag value from a flat argv-style token list."""
    if not tokens:
        return None
    for idx, token in enumerate(tokens):
        if token == flag and idx + 1 < len(tokens):
            return str(tokens[idx + 1]).strip()
        if token.startswith(f"{flag}="):
            return token.split("=", 1)[1].strip()
    return None


def _deduplicate_path(path: Path) -> Path:
    """Append ``_1``, ``_2`` ... until the path becomes unique."""
    if not path.exists():
        return path
    i = 1
    while True:
        candidate = path.with_name(f"{path.name}_{i}")
        if not candidate.exists():
            return candidate
        i += 1


def _build_user_run_command(
    *,
    skill_name: str,
    demo: bool,
    input_path: str | None,
    output_dir: Path,
    forwarded_args: list[str] | None = None,
) -> list[str]:
    """Build a user-facing ``oc run`` command for provenance and notebooks."""
    cmd = ["oc", "run", skill_name]
    if demo:
        cmd.append("--demo")
    elif input_path:
        cmd.extend(["--input", input_path])
    cmd.extend(["--output", str(output_dir)])
    if forwarded_args:
        cmd.extend(forwarded_args)
    return cmd


def _finalize_output_directory(
    out_dir: Path,
    *,
    skill_name: str,
    skill_info: dict[str, Any],
    timestamp: str,
    user_supplied_output_dir: bool,
    preferred_method: str | None = None,
    actual_command: list[str] | None = None,
) -> tuple[Path, str | None, str, str, dict[str, Any] | None]:
    """Rename autogenerated output dirs and generate human-readable artifacts."""
    payload = load_result_json(out_dir)
    actual_method = extract_method_name(payload, fallback=preferred_method)
    final_dir = out_dir
    notebook_command = list(actual_command) if actual_command else None

    if not user_supplied_output_dir and actual_method:
        desired_name = build_output_dir_name(skill_name, timestamp, method=actual_method)
        desired_path = _deduplicate_path(out_dir.with_name(desired_name))
        if desired_path != out_dir:
            try:
                out_dir.rename(desired_path)
                final_dir = desired_path
            except OSError:
                final_dir = out_dir

    if notebook_command:
        for idx, token in enumerate(notebook_command):
            if token == "--output" and idx + 1 < len(notebook_command):
                notebook_command[idx + 1] = str(final_dir)
                break

    notebook_path = _get_write_analysis_notebook()(
        final_dir,
        skill_alias=skill_name,
        description=skill_info.get("description", ""),
        result_payload=payload,
        preferred_method=actual_method,
        script_path=skill_info.get("script"),
        actual_command=notebook_command,
    )
    readme_path = write_output_readme(
        final_dir,
        skill_alias=skill_name,
        description=skill_info.get("description", ""),
        result_payload=payload,
        preferred_method=actual_method,
        notebook_path=notebook_path,
    )
    return final_dir, actual_method, str(readme_path), str(notebook_path), payload


def _write_pipeline_readme(
    output_dir: Path,
    *,
    pipeline_name: str,
    results: dict[str, Any],
    completed_at: str,
) -> Path:
    """Write a top-level README for pipeline outputs."""
    lines = [
        "# OmicsClaw Pipeline Output Guide",
        "",
        "## Overview",
        "",
        f"- **Pipeline**: `{pipeline_name}`",
        f"- **Completed at**: `{completed_at}`",
        "- Open the per-step `README.md` inside each step folder for the method, parameters, and output map.",
        "- Open each step's `reproducibility/analysis_notebook.ipynb` for a code-first walkthrough.",
        "",
        "## Steps",
        "",
        "| Step | Status | Method | Output | Notebook |",
        "|------|--------|--------|--------|----------|",
    ]

    for step_name, info in results.items():
        status = "success" if info.get("success") else "failed"
        method = info.get("method") or "-"
        output_name = Path(info.get("output_dir", step_name)).name if info.get("output_dir") else "-"
        notebook_name = Path(info.get("notebook_path", "")).name if info.get("notebook_path") else "-"
        lines.append(f"| `{step_name}` | `{status}` | `{method}` | `{output_name}` | `{notebook_name}` |")

    lines.extend(["", "## Folder Contents", ""])
    for path in sorted(output_dir.iterdir(), key=lambda p: (p.is_file(), p.name.lower())):
        suffix = "/" if path.is_dir() else ""
        lines.append(f"- `{path.name}{suffix}`")

    readme_path = output_dir / "README.md"
    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return readme_path


def _stream_to_sink(
    stream,
    sink: list[str],
    callback: Callable[[str], None] | None,
) -> None:
    """Drain ``stream`` line-by-line into ``sink`` and forward to ``callback``.

    ``callback`` receives each line stripped of its trailing newline. Callback
    exceptions are swallowed so a buggy log handler cannot abort the run.
    """
    try:
        for line in iter(stream.readline, ""):
            if not line:
                break
            sink.append(line)
            if callback is not None:
                try:
                    callback(line.rstrip("\n"))
                except Exception:
                    # The skill must complete even if the consumer's logger blows up.
                    pass
    finally:
        try:
            stream.close()
        except Exception:
            pass


def run_skill(
    skill_name: str,
    *,
    input_path: str | None = None,
    input_paths: list[str] | None = None,
    output_dir: str | None = None,
    demo: bool = False,
    session_path: str | None = None,
    extra_args: list[str] | None = None,
    stdout_callback: Callable[[str], None] | None = None,
    stderr_callback: Callable[[str], None] | None = None,
    cancel_event: threading.Event | None = None,
) -> dict:
    """Run a single skill via subprocess and return a stable result dict.

    When ``stdout_callback`` / ``stderr_callback`` are supplied the runner
    invokes them once per line as the skill emits output (newline stripped),
    so long-running skills produce visible logs in real time. Aggregated
    ``stdout`` / ``stderr`` strings are still returned in the result dict.

    When ``cancel_event`` is supplied the runner watches it; if the event is
    set while the skill is running the child process group receives SIGTERM,
    waits a short grace period, then SIGKILL, ensuring cancelled jobs do not
    leak children consuming CPU/GPU until natural completion.
    """
    skill_name = resolve_skill_alias(skill_name)

    if skill_name == "spatial-pipeline":
        return _run_spatial_pipeline(
            input_path=input_path,
            output_dir=output_dir,
            demo=demo,
            session_path=session_path,
        )

    skill_info = SKILLS.get(skill_name)
    if skill_info is None:
        return _err(skill_name, f"Unknown skill '{skill_name}'. Available: {list(SKILLS.keys())}")

    script_path: Path = skill_info["script"]
    if not script_path.exists():
        return _err(skill_name, f"Script not found: {script_path}")

    resolved_input_paths: list[str] | None = None
    if input_paths and len(input_paths) >= 2:
        resolved_input_paths = [str(Path(p).resolve()) for p in input_paths]

    resolved_input = input_path
    if session_path and not input_path and not demo and not resolved_input_paths:
        from omicsclaw.common.session import SpatialSession

        session = SpatialSession.load(session_path)
        if session.h5ad_path:
            resolved_input = session.h5ad_path

    if resolved_input:
        resolved_input = str(Path(resolved_input).resolve())

    user_supplied_output_dir = output_dir is not None
    generated_ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    requested_method = _extract_flag_value(extra_args, "--method")

    if output_dir:
        out_dir = Path(output_dir).resolve()
    else:
        auto_name = build_output_dir_name(skill_name, generated_ts, method=requested_method)
        out_dir = _deduplicate_path(DEFAULT_OUTPUT_ROOT / auto_name)
    out_dir.mkdir(parents=True, exist_ok=True)

    cmd = [PYTHON, str(script_path)]
    if demo:
        cmd.extend(skill_info["demo_args"])
    elif resolved_input_paths:
        for path in resolved_input_paths:
            cmd.extend(["--input", path])
    elif resolved_input:
        cmd.extend(["--input", str(resolved_input)])
    else:
        return _err(skill_name, "No --input, --demo, or --session provided.")

    cmd.extend(["--output", str(out_dir)])

    domain = skill_info.get("domain", "unknown")
    domain_display = DOMAINS.get(domain, {}).get("name", domain.title())
    if demo:
        mode_str = f"{CYAN}demo mode{RESET}"
    elif resolved_input_paths:
        mode_str = f"inputs: {', '.join(resolved_input_paths)}"
    else:
        mode_str = f"input: {resolved_input}"
    print(f"\n{BOLD}Running {domain_display} skill:{RESET} {GREEN}{skill_name}{RESET} ({mode_str})")
    print(f"{BOLD}Output:{RESET} {out_dir}\n")

    def _is_numeric_literal(token: str) -> bool:
        return bool(re.fullmatch(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?", token))

    def _next_token_is_value(tokens: list[str], idx: int) -> bool:
        if idx + 1 >= len(tokens):
            return False
        nxt = tokens[idx + 1]
        if not nxt.startswith("-"):
            return True
        return _is_numeric_literal(nxt)

    filtered: list[str] = []
    if extra_args:
        allowed = skill_info.get("allowed_extra_flags", set())
        blocked = {"--input", "--output", "--demo"}
        i = 0
        while i < len(extra_args):
            token = extra_args[i]
            flag = token.split("=")[0]
            has_inline_value = "=" in token

            if flag == "--n-epochs" and "--n-epochs" not in allowed and "--epochs" in allowed:
                token = token.replace("--n-epochs", "--epochs", 1)
                flag = "--epochs"
            elif flag == "--epochs" and "--epochs" not in allowed and "--n-epochs" in allowed:
                token = token.replace("--epochs", "--n-epochs", 1)
                flag = "--n-epochs"

            if flag in blocked:
                i += 2 if (not has_inline_value and _next_token_is_value(extra_args, i)) else 1
                continue
            if flag in allowed:
                filtered.append(token)
                if not has_inline_value and _next_token_is_value(extra_args, i):
                    filtered.append(extra_args[i + 1])
                    i += 1
            i += 1
        cmd.extend(filtered)

    t0 = time.time()
    try:
        env = os.environ.copy()
        env["PYTHONPATH"] = str(OMICSCLAW_DIR) + os.pathsep + env.get("PYTHONPATH", "")
        popen = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,  # line-buffered so callbacks fire as the skill prints
            cwd=str(script_path.parent),
            env=env,
            start_new_session=True,
        )

        def _reaper():
            """Wait for main process exit, then kill orphaned siblings."""
            popen.wait()
            time.sleep(0.5)
            try:
                os.killpg(os.getpgid(popen.pid), 9)
            except (ProcessLookupError, PermissionError, OSError):
                pass

        def _cancel_watcher():
            """Send SIGTERM (then SIGKILL after grace) when cancel_event is set."""
            if cancel_event is None:
                return
            while popen.poll() is None:
                if cancel_event.wait(timeout=0.2):
                    try:
                        os.killpg(os.getpgid(popen.pid), signal.SIGTERM)
                    except (ProcessLookupError, PermissionError, OSError):
                        return
                    grace_deadline = time.time() + 5.0
                    while popen.poll() is None and time.time() < grace_deadline:
                        time.sleep(0.1)
                    if popen.poll() is None:
                        try:
                            os.killpg(os.getpgid(popen.pid), signal.SIGKILL)
                        except (ProcessLookupError, PermissionError, OSError):
                            pass
                    return

        reap_thread = threading.Thread(target=_reaper, daemon=True)
        reap_thread.start()
        cancel_thread: threading.Thread | None = None
        if cancel_event is not None:
            cancel_thread = threading.Thread(target=_cancel_watcher, daemon=True)
            cancel_thread.start()

        stdout_lines: list[str] = []
        stderr_lines: list[str] = []
        stdout_thread = threading.Thread(
            target=_stream_to_sink,
            args=(popen.stdout, stdout_lines, stdout_callback),
            daemon=True,
        )
        stderr_thread = threading.Thread(
            target=_stream_to_sink,
            args=(popen.stderr, stderr_lines, stderr_callback),
            daemon=True,
        )
        stdout_thread.start()
        stderr_thread.start()

        try:
            popen.wait()
        except Exception:
            pass
        stdout_thread.join(timeout=5)
        stderr_thread.join(timeout=5)
        reap_thread.join(timeout=5)
        if cancel_thread is not None:
            cancel_thread.join(timeout=5)

        stdout = "".join(stdout_lines)
        stderr = "".join(stderr_lines)
        return_code = popen.returncode or 0
        # The ``-9 → 0`` heuristic was a workaround for the orphan reaper's
        # SIGKILL race when the main process had already produced its
        # ``result.json``. Once ``cancel_event`` was wired to escalate to
        # SIGKILL, ``-9`` also became the *normal* outcome of cancellation.
        # Skip the heuristic when the run was actually cancelled, otherwise a
        # cancelled run that happened to leave a partial ``result.json``
        # would be silently reported as success.
        was_cancelled = cancel_event is not None and cancel_event.is_set()
        if (
            not was_cancelled
            and return_code == -9
            and (Path(out_dir) / "result.json").exists()
        ):
            return_code = 0
        proc = subprocess.CompletedProcess(cmd, return_code, stdout, stderr)
    except Exception as exc:
        duration = time.time() - t0
        return _err(skill_name, str(exc), duration=duration)

    duration = time.time() - t0

    final_out_dir = out_dir
    actual_method = requested_method
    readme_path = ""
    notebook_path = ""
    if proc.returncode == 0:
        user_command = _build_user_run_command(
            skill_name=skill_name,
            demo=demo,
            input_path=resolved_input,
            output_dir=out_dir,
            forwarded_args=filtered,
        )
        final_out_dir, actual_method, readme_path, notebook_path, _ = _finalize_output_directory(
            out_dir,
            skill_name=skill_name,
            skill_info=skill_info,
            timestamp=generated_ts,
            user_supplied_output_dir=user_supplied_output_dir,
            preferred_method=requested_method,
            actual_command=user_command,
        )

    output_files = sorted(
        [path.name for path in final_out_dir.rglob("*") if path.is_file()]
    ) if final_out_dir.exists() else []

    result = build_skill_run_result(
        skill=skill_name,
        success=proc.returncode == 0,
        exit_code=proc.returncode,
        output_dir=final_out_dir,
        files=output_files,
        stdout=proc.stdout,
        stderr=proc.stderr,
        duration_seconds=duration,
        method=actual_method,
        readme_path=readme_path,
        notebook_path=notebook_path,
    ).to_legacy_dict()

    if session_path and result["success"]:
        _store_result_in_session(session_path, skill_name, final_out_dir)

    return result


def _run_spatial_pipeline(
    input_path: str | None = None,
    output_dir: str | None = None,
    demo: bool = False,
    session_path: str | None = None,
) -> dict:
    """Run the standard spatial analysis pipeline end-to-end."""
    if not input_path and not session_path and not demo:
        return _err("spatial-pipeline", "Requires --input, --demo, or --session.")

    if output_dir:
        out_dir = Path(output_dir)
    else:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_dir = DEFAULT_OUTPUT_ROOT / build_output_dir_name("spatial-pipeline", ts)
    out_dir.mkdir(parents=True, exist_ok=True)

    all_results: dict[str, Any] = {}
    current_input = input_path

    for skill_name in SPATIAL_PIPELINE:
        skill_out = out_dir / skill_name
        print(f"  Running {skill_name}...")
        result = run_skill(
            skill_name=skill_name,
            input_path=current_input,
            output_dir=str(skill_out),
            demo=demo and current_input is None,
            session_path=session_path,
        )
        all_results[skill_name] = {
            "success": result["success"],
            "duration": result["duration_seconds"],
            "method": result.get("method"),
            "output_dir": result.get("output_dir", ""),
            "readme_path": result.get("readme_path", ""),
            "notebook_path": result.get("notebook_path", ""),
        }
        if not result["success"]:
            print(f"{RED}FAILED{RESET}: {skill_name}")
            if result.get("stderr"):
                print(f"    {result['stderr'][:200]}")
            break

        processed = skill_out / "processed.h5ad"
        if processed.exists():
            current_input = str(processed)

    completed_at = datetime.now(timezone.utc).isoformat()
    summary = {
        "pipeline": SPATIAL_PIPELINE,
        "results": all_results,
        "completed_at": completed_at,
    }
    summary_path = out_dir / "pipeline_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, default=str))
    pipeline_readme = _write_pipeline_readme(
        out_dir,
        pipeline_name="spatial-pipeline",
        results=all_results,
        completed_at=completed_at,
    )

    succeeded = sum(1 for result in all_results.values() if result["success"])
    return build_skill_run_result(
        skill="spatial-pipeline",
        success=succeeded == len(SPATIAL_PIPELINE),
        exit_code=0 if succeeded == len(SPATIAL_PIPELINE) else 1,
        output_dir=out_dir,
        files=[path.name for path in out_dir.rglob("*") if path.is_file()],
        stdout=f"Pipeline: {succeeded}/{len(SPATIAL_PIPELINE)} skills succeeded.",
        stderr="",
        duration_seconds=sum(result["duration"] for result in all_results.values()),
        readme_path=pipeline_readme,
        notebook_path="",
    ).to_legacy_dict()


def _store_result_in_session(session_path: str, skill_name: str, out_dir: Path) -> None:
    """Store skill result back into the session JSON."""
    try:
        from omicsclaw.common.session import SpatialSession

        result_json = out_dir / "result.json"
        if not result_json.exists():
            return
        session = SpatialSession.load(session_path)
        result_data = json.loads(result_json.read_text())
        session.add_skill_result(skill_name, result_data, output_dir=str(out_dir))

        processed = out_dir / "processed.h5ad"
        if processed.exists():
            session.h5ad_path = str(processed)
            session.mark_step(skill_name)

        session.save(session_path)
    except Exception:
        pass


def _err(skill: str, msg: str, duration: float = 0) -> dict:
    return build_skill_run_result(
        skill=skill,
        success=False,
        exit_code=-1,
        output_dir=None,
        stderr=msg,
        duration_seconds=duration,
    ).to_legacy_dict()
